### ISSUE TITLE
EnergyDay and EnergyYear will return Null and an error on GEN24/Tauro inverters

### ISSUE THREAD

**Issue by avyeegaztd** [ccremer/fronius-exporter#127]
According to the Fronius Solar API V1 documentation, these two values will always report null when polled. Actually, all archival data (GetArchiveData) is unsupported by the API and only real-time data is provided. 
fronius-exporter will report all values, but still throws an error for these two entries. Either make a switch for GEN24/Tauro users to disable generation of these entries, or at least don't count them as errors.

I am actually sure that Fronius still has an undocumented archive request in place for GEN24/Tauro inverters, because after in installed the inverter and connected it to Solarweb it caught up the missing timeframe at least in 5 minute intervals and of course it plotted the graph for the three days it wasn't connected and reported the total for these days.

**Comment by ccremer** [comment]
Hi
I don't quite follow. GetArchiveData is called only if `--symo.enable-archive` is enabled. Have you enabled this flag?

**Comment by avyeegaztd** [comment]
The comment on the archive was a general observation. I assume that EnergyDay is considered archival data. 

I started the exporter with
`fronius-exporter -v --symo.url http://InverterIP`
Loading the metrics page i get this error

```
DEBU[0003] Parsing data.                                 powerFlowData="{map[1:{1 1718.44482421875 0 0 0 270857.6036111111}] {produce-only unknown 0 0 0 1825.461669921875 0 0 0 0 270857.6036111111}}"
WARN[0003] Could not collect Symo archive metrics.       error="invalid character '<' looking for beginning of value"
DEBU[0003] Parsing data.                                 InverterRealtimeData="{{A 3.6999263763427734} {A 0} {A 0} {A 0} {V 490.5227355957031} {V 0} {V 0} {V 0} {Hz 50.01508712768555} {W 1718.44482421875} {Wh 270857.6036111111}}"
```

**Comment by ccremer** [comment]
> "invalid character '<' looking for beginning of value"

Looks like the response is not JSON, probably an HTML error page.

What is the output of
`curl http://InverterIP/solar_api/v1/GetArchiveData.cgi?Scope=System&Channel=Voltage_DC_String_1&Channel=Current_DC_String_1&Channel=Voltage_DC_String_2&Channel=Current_DC_String_2&HumanReadable=false` ?

**Comment by avyeegaztd** [comment]
Oh, I see.
I think I misidentified the issue.
```
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
 </body>
</html>

^C
[1]-  Done                    curl InverterIP/solar_api/v1/GetArchiveData.cgi?Scope=System
[5]+  Done                    Channel=Current_DC_String_2
```

So it just throws an error because the GetArchivData.cgi is not implemented on GEN24/Tauro? (As per the API pdf 42,0410,2012,EN 01928112023 on page 72)

**Comment by ccremer** [comment]
Yes, looks like it.
You can disable the scraping of this endpoint with `--symo.enable-archive=false`
