### ISSUE TITLE
Archive data stuck the day after change from daylight savings to normal time

### ISSUE THREAD

**Issue by tongpu** [ccremer/fronius-exporter#129]
I just had the issue yesterday (change from CEST to CET) that the exporter was stuck reporting the data it ingested at 2024-10-27 01:00 UTC (2024-10-27 03:00 CEST/2024-10-27 02:00 CET).

This could easily be an issue with the archive API of the inverter, I thought I'd just drop this here to see if anyone else is having the same issues.

Important note to add: Today on 2024-10-28 everything returned to normal without any intervention.

**Comment by tongpu** [comment]
I also just found this comment in section 5.1.1 of the Fronius Solar API V1 PDF. :sweat_smile: 

> On days where daylight saving time is changing (begin or end of summertime) a few problems are
known regarding time calculation.

**Comment by ccremer** [comment]
Hi. Thanks for reporting this!
Glad to hear that everything's back to normal.

I'm going to close this as I don't see an action point here.
