### ISSUE TITLE
Verify deb package signature.

### ISSUE THREAD

**Issue by baduhai** [ccremer/fronius-exporter#18]
I would like to verify your signatures but could not manage to find your public key. Can you point me to it? 
Thanks for the work on the exporter, it works perfectly for what I needed.

**Comment by ccremer** [comment]
Hi!
It's here: https://github.com/ccremer/fronius-exporter/blob/master/.github/signature.asc, or use the version that is according with the git tag/release you're using, probably more stable than master branch.

I didn't know that someone is using it :see_no_evil: I'm not yet using it even for myself :)

**Comment by baduhai** [comment]
Perfect, thanks once again for your work!
